name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [20, 22]
        template: [default, typescript]
    uses: yoriiis/actions/.github/workflows/test-and-build.yml@main
    with:
      node-version: ${{ matrix.node-version }}
      command-build: node bin/cli.js sandbox --template ${{ matrix.template }}
